apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lechatbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lechatbot 
  name: lechatbot
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: lechatbot 
